### ISSUE TITLE
Activity Main Screens: Checklist

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#1932]
- [x]   1. Activity item-view and view mostly use the default ERC 20/721 TokenScript
- [x]   2. Default attribute override e.g. name, for ERC20 tokens that lack name()
- [x]   3. Default card override
- [ ]   4. Activities that happen between last time you opened wallet
- [x]   5. Manage performance when rendering <item-view> (refer A3 for comparison of 2 methods)
- [x]   6. Move transaction details to 'hamburger menu' on activity card
- [x]   7. For transactions with multiple events, users will not be seeing them grouped together
- [x]   8. Incorporate Status icons (only the three done types)
- [x]   9.  Failed transactions and mysterious transactions are handled like Transaction Tab.
- [x]   10.  Render ETH send/receive with the look of an activity.
  11. Cross platform attribute dependency graph (optional and to be produced by Weiwu) 

A3 Link: https://drive.google.com/file/d/1YqUlHInPa1MldLq30mxXGHkkJT5cbOlL/view?usp=sharing

Note from Weiwu for devs
    a. Recommended to create new activity view, rather than tweaking code from another existing view. 
    b. Hide transaction view

**Comment by hboon** [comment]
Closed with #2180
