### ISSUE TITLE
Umbrella issue for iOS 14

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#1967]
- [ ] split items into separate issues
- [ ] Checking the pasteboard, especially on startup has to be removed or replaced with using the new API to check for URLs. Otherwise launching or resuming the app always show a pop up saying it's checking the pasteboard
- [ ] Location permissions are more granular
