### ISSUE TITLE
Scope for 30th October 

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2223]
Can we list out our key focuses for this fortnight?

**Comment by hboon** [comment]
- [x] Fix: timestamp not appearing in Activity tab for native crypto transfers #2206
- [x] Fix: default ERC20 send/receive activities always assumed (wrongly) that token decimals = 18 #2207
- [x] Refactor transaction gas price limit estimating #2209
- [x] Fix: ERC721 transfer button not showing up after tapping on an ERC721 token instance #2212
- [x] Update Eth token icon #2213
- [x] Add CoFi token icon #2214
- [x] Fix: token balance refreshing in wallet tab is way too slow #2215
- [x] Automatically select all text in textfield in gas configuration screen when the textfield is tapped for better usability #2216
- [x] Remove spurious comment #2217
- [x] Refactor: remove most `Wallet?` references for current wallet to get rid of optionals #2219
- [x] Remove unused code #2220
- [x] Update CoFi token icon and add X-Token 1 icon #2222
- [ ] Get scoped down actionsheet for normal transactions merged, to continue with follow up work #2105
- [ ] Fix build warnings #2221
- [ ] iPad token icon for activity under nav bar
- [ ] Looks wrong: $0.1["contractAddress"].description == contractAddress.eip55String.lowercased()

**Comment by hboon** [comment]
Build 360

**Comment by AW-STJ** [comment]
Notifications are working!!! Yay....

> * [x]  Fix: timestamp not appearing in Activity tab for native crypto transfers #2206
Working correctly on 3.08(360)
> * [x]  Fix: default ERC20 send/receive activities always assumed (wrongly) that token decimals = 18 #2207
Working, with correct balances on 3.08(360). However have 0 balance on activity card, raised as separate bug #2240 
> * [x]  Refactor transaction gas price limit estimating #2209
Working similar to android. However not the same as Ethergas estimator. #2242
> * [x]  Fix: ERC721 transfer button not showing up after tapping on an ERC721 token instance #2212
Transfer button working for ENS
> * [x]  Update Eth token icon #2213
Eth token icon is blue. @colourfreak - should it be blue? Then will push this for Android as well.
> * [x]  Add CoFi token icon #2214
> * [x]  Fix: token balance refreshing in wallet tab is way too slow #2215
Token Balance is updating reasonable fast
> * [x]  Automatically select all text in textfield in gas configuration screen when the textfield is tapped for better usability #2216
Wokring well and great experience. Good one
> * [x]  Remove spurious comment #2217
> * [x]  Refactor: remove most `Wallet?` references for current wallet to get rid of optionals #2219
> * [x]  Remove unused code #2220
> * [x]  Update CoFi token icon and add X-Token 1 icon #2222
> * [x]  Fix build warnings #2221
> * [x]  Fix: Activity view is clipped by navigation bar on iPad #2224
> * [x]  Looks wrong: $0.1["contractAddress"].description == contractAddress.eip55String.lowercased()
> * [ ]  WIP — Get scoped down actionsheet for normal transactions merged, to continue with follow up work #2105
