### ISSUE TITLE
Scope for 13 Nov

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2239]
- [x] Actionsheet for transactions. There'll be some follow up that isn't included. #2105
- [x] Display failed transactions in Activity tab #2254
- [x] Vibrate after adding bookmark #2260 #2262
- [x] Make camera button in address textfield follow textfield's background color #2253 #2256
- [x] Make back, forward, "more" button in Browser navigation bar be highlighted like QR scan button in Wallet tab when tapped and held #2246 #2248
- [x] Add search functionality to Activity tab #2258 #2261 (rudimentary, will make it more powerful. Possibly #2272)

**Comment by hboon** [comment]
Build 361
