### ISSUE TITLE
Scope for 27 Nov

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2271]
- [x] Use Actionsheet for claiming paid MagicLinks #2300
- [x] Display estimated time based on gas settings #2309
- [x] Display the ETH value in actionsheet for transaction initiated by dapp #2304
- [x] Show name of token for ERC721 transfers (at least those from OpenSea) #2305
- [x] Fix: Gas fee estimate in fiat should be displayed when editing custom gas for transaction on mainnet #2303
- [x] Display estimated gas fee (and in fiat too, if available) in actionsheet for transaction confirmation #2302
- [x] Fix: if enter "" for eth when sending ETH, should show "0 ETH" instead of " ETH" #2301
- [x] Raise gas fee max to 3 ETH #2297
- [x] Remove trailing zeros from Amount Text Field added during switch from crypty to native currency #2291 #2292
- [x] Open URL in AlphaWallet using share extension doesn't convert % escapes #2289 #2290
- [x] Track events for actionsheet-style confirmation transactions #2199 #2282
- [x] In Activity tab, show "All <symbol>" instead of an very long string of numbers that garbles the display for ERC20 approvals for very large amounts #2280

**Comment by AW-STJ** [comment]
Suggestions to consider:
- [ ] Wallet Connect: https://github.com/AlphaWallet/alpha-wallet-ios/pull/2012

**Comment by hboon** [comment]
> * [ ]  Wallet Connect: #2012

Vlad can continue to work on it in the background, but might not be able to finish it, mainly because there's no one to point him in the right direction. I could look at it once I'm done with the followups for Actionsheet for transactions.

**Comment by hboon** [comment]
Build 365
