### ISSUE TITLE
Scope for 11 Dec

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2344]
Actionsheet for transaction confirmation
---
- [x] Please display the nonce number in the Custom page #2336
- [x] Refresh gas price in "Custom" cell when editing Custom setting for transaction #2366
- [x] Do not show "ENS" label in Actionsheet for transaction confirmation under Recipient if there is no ENS name resolved (yet) #2310
- [x] Show gas price for each option while editing/choosing gas options for actionsheet for transaction confirmation #2371
- [x] Decode ERC20 transfers for dapp-initiated transactions and display in actionsheet #2337 
- [x] Make text color red in textfields in actionsheet if there are warnings/earrors while editing gas settings #2382
- [x] Show warnings for high/low/congested gas prices in actionsheet for transaction confirmation and editing gas option screen #2378
- [x] Expand hit test area for Recipient cell in actionsheet for transaction confirmation so that when it's expanded, tapping on the expanded area closes it too (like it does when tapping the upper half of the cell) #2364
- [x] Expand hit-test area for Edit button in actionsheet for transaction confirmation to the entire cell #2363
- [x] Fix: custom gas price appears as 1 in edit custom gas screen if we set it to >= 1000 and saved it #2386
- [x] Make gas limit and gas fee exceed threshold error messages appear immediately rather than wait until user taps Save button #2384

Activity
---
- [x] Make search in activities support the token symbol #2272
- [x] Add support for searching with activity name and token symbol names in Activity tab at the same time. eg. `sent cofi` #2345
- [x] Speed up search activities #2345
- [x] Show "All <token symbol>" in activity screen after tapping an activity in Activity tab which is for approving large amounts of ERC20 transfers #2343

Others
---
- [x] Push instead of present modal the Wallet Address screen (the one with QR code) #2375
- [x] In ERC20 token swap using OneInch, make the target token be USDT (if from ETH), and ETH (otherwise) #2346

Other fixes
---
- [x] Fix: Crash if tap camera button while importing a wallet while onboarding #2352
- [x] Update binance endpoints #2355
- [x] Remove tab bar appearing briefly after tapping "Go to Token" to show token #2342
- [x] Crash with large wallet #2341

WIP/Pending
---
- [ ] Make Fastlane for uploading to App Store connect work again #2306
- [ ] Face ID doesn't show up after the transaction confirmation popup with the error message 'cancelled'. #2284
- [ ] Maybe: Wallet Connect: #2012

**Comment by hboon** [comment]
Build 367
