### ISSUE TITLE
Scope for 8 Jan

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2425]
WalletConnect
---
- [x] WalletConnect now supports multi-sessions
- [x] Let user choose the server to use WalletConnect against; no longer connecting to the one set in the dapp browser
- [x] Use the chainId in the WalletConnect connection request, if provided and don't ask the user to choose chain #2440 
- [x] Tweak label in cell to show WalletConnect sessions in Wallet tab. Also plural form when there are more than 1 session
- [x] Remove the Signed Transactions cell from the WalletConnect session screen, which does nothing when tapped anyway #2421
- [x] Fix: Make EIP712v3 support for WalletConnect work correctly
- [x] Fix: make gas and Ether `value` in fiat appear in actionsheet for confirming transactions initiated by WalletConnect #2419
- [x] Fix: use correct AlphaWallet URL when broadcasting as a client for WalletConnect session
- [x] Support eth_getTransactionCount for WalletConnect correctly #2418 

Binance
---
- [x] Add token icon for Binance mainnet
- [x] Label Binance testnet as testnet for clarity

Others
---
- [x] Support Heco #2411
- [x] Fix: Send 10 tokens but only receives 1 #2408
- [x] Fix: ERC20 token transactions are sent wrong to the recipient address. Should send to contract instead #2415

**Comment by hboon** [comment]
Build 370
