### ISSUE TITLE
Scope for 5 Feb

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2478]
- [x] Display internal transactions as a group of transactions in Activity tab #2502
- [x] Replace xDai bridge TokenScript action with hardcoded link to xDai bridge dapp
- [x] Display pretty error for failed transaction #2487
- [x] Fix: Should selectively auto disconnect all WalletConnect sessions when restarting wallet #2474
- [x] Fix issue with Navigation bar for Activity tab stuck at non-large mode after opening token from activity #2493

Backlog

- [ ] Cancel/Speed up transactions

**Comment by hboon** [comment]
TestFlight build 373
