### ISSUE TITLE
Scope for 19 Feb

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2503]
- [x] Integrate Ramp to buy xDai as action in xDai token screen #2530
- [x] Add send all funds button #2450
- [x] Display internal transactions as a group of transactions in Activity tab
- [x] Support EIP1193 (and hence https://web3modal.com) #2499

WalletConnect
---
- [x] Fix: handle WalletConnect links when the mobile link is launched in dapp browser #2529 #2498
- [x] Fix: parse WalletConnect links picked up from mobile linking #2528 #2498

Signing
---
- [x] Fix: prompt to sign message is empty when the message is very long #2455

UI
---
- [x] action sheets need to show which network I am using for the current TX #2518
- [x] Change several screens which were presented modally to push/pop — transaction view, receive/address screeen, edit dapp/favorites, send token, console
- [x] Fix: unexpected bottom inset which appears while resuming from background #2466
- [x] Fix: tapping on Swap (token) button switches to dapp browser. But if it already displays another site, it wouldn't load 1inch #2524

Internal
---
- [x] Code clean ups
- [x] Fix: Disable error about malformed JSON if it appears to be caused by Binance testnet timing out (as there's nothing we can do about it) #2532

Backlog
---
- [ ] Cancel/Speed up transactions

**Comment by AW-STJ** [comment]
#2499 can be a good one for the next sprint, if possible

**Comment by AW-STJ** [comment]
Also, displaying the correct error for 'Insufficient funds for gas' issue is popping up again and got a couple of queries from users over the weekend:
https://github.com/AlphaWallet/alpha-wallet-ios/issues/2441

**Comment by hboon** [comment]
Build 378
