### ISSUE TITLE
Scope 5 Mar

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2538]
- [x] Disable "All Funds" for fungibles (fixing a bug)

On-ramp
---
- [x] Make Ramp (by crypto with fiat) available for other tokens #2587 #2591

Swaps
---
- [x] xDAI + Honeyswap #2537 #2540

UI
---
- [x] Add "Show Seed Phrase" to Settings tab #2582 #2589
- [x] Deeplink FAQ from the Settings to AlphaWallet.com/faq #2583 #2588
- [x] Fix web3swift memory leaks #2584 #2586
- [x] Back up seed phrase introduction screen text is clipped in iPhone 6s #2564 #2574
- [x] Remove App Intro Slides #2552 #2561
- [x] Add a custom graphic for empty activites #2553 #2560
- [x] Update xDai token icon #2535 #2548
- [x] Refreshed prompts to sign messages #2497 #2549

Analytics
---
- [x] Log number of wallets #2578
- [x] Log transaction failed #2579
- [x] Log browser events #2580

Wallet Connect fixes
---
- [x] WalletConnect using mobile linking crashes if the chain is disabled #2609 #2614
- [x] WalletConnect memory leaks #2602 #2603

Performance and Internals
---
- [x] Remove unnecessary call to name and symbol for ENS token #2613
- [x] Reduce TransactionsStorage instances #2605 #2606
- [x] TokenViewController is not released after popping #2595 #2601
- [x] Refactor: Separate out client code that logs to analytics #2577
- [x] Tweak error logging to be more granular #2576

User-friendly messages
---
- [x] Fix: error message shown when user doesn't have enough funds for sending a transaction (send amount + gas) is not user friendly #2556
- [x] Tweak (internal) logging of errors to collect them

Other fixes
---
- [x] Fix: TokenScript attributes are not resolved #2611
- [x] Sometimes crashes when disabling a chain in Settings #2597 #2600
- [x] Launch swap service from token to dapp browser should always switch to correct chain #2555

Backlog

- [ ] Cancel/Speed up transactions (poor thing, has been shoved around)

**Comment by hboon** [comment]
Build 382
