### ISSUE TITLE
Scope for 19 Mar

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2620]
- [ ] WIP — Cancel/Speed up transactions (poor thing, has been shoved around) #2619 
- [x] Tai Chi support #2489
- [x] Add more EVM-based networks: Polygon, Avalanche, Fantom and testnets.

WalletConnect
---
- [x] Can't detect when the server selection screen is closed (via back button) in the WalletConnect open session screen. #2644
- [x] When switching servers for a new WalletConnect session, the default/chosen server should be checked #2643
- [x] If we reject a WalletConnect connection, we are stuck in the list of sessions screen #2642
- [x] Show error message if dapp selects a chain for WalletConnect that is disabled in the app #2652
- [x] Tweak WalletConnect error message #2648

UI tweaks
---
- [x] Improve Pending Transaction icon & Background in Activity tab #2650
- [x] Tweak back up seed phrase introduction copy #2649

Make error messages more user friendly
---
- [x] Tweak error logging to be more granular #2636
- [x] Tweak error logging to be more granular #2640
- [ ] WIP — Make errors more user friendly #2557 — have collected error messages. Pending user-friendly replacements

Analytics
---
- [x] Log to analytics WalletConnect #2647 
- [x] Log to analytics message signing prompts #2645

Internal
---
- [x] Also pass AnalyticsCoordinator to `EtherKeystore` when creating in `TokenInstanceWebView`
- [x] Refactor: pass AnalyticsCoordinator around for future logging support
- [x] Remove debug print #2641 
- [x] Fix: tests are not building #2638
- [x] Add test case to check AmountTextField displays correctly formatted string #2612

Other bug fixes
---
- [x] Fix: Send "All Funds" adding decimal separator "," for locales (regions) that use it breaks the send function #2590
- [x] Fix: amount of ERC20 to send in actionsheet for transaction confirmation is displayed incorrectly #2635

**Comment by hboon** [comment]
Build 385
