### ISSUE TITLE
Scope for 2 Apr

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2656]
- [x] Speedup and cancel transactions from Activity tab #2669

UI tweaks
---
- [x] Remove "Save" button from Select Active Networks #2660
- [x] Move TaiChi option to advanced settings section #2658
- [x] Provide better icon for TaiChi in the Settings #2657
- [x] Improve Pending Transaction icon & Background in Activity tab #2650

Bug fixes/workarounds
---
- [x] Load TokenScript file even if signature verification fails (because signature verification web API isn't working properly) #2682
- [x] Wrong amount in Send actionsheet #2661
- [x] Hide, and disable language switcher #2681 (disable until/if we can get it to work properly again)
- [x] Fix: display of "to" address for ERC20 and other token transfers are wrong for pending transactions in the transaction view — shows the contract rather than the recipient #2674

Internal
---
- [x] Upgrade cocoapods gem #2685
- [x] Fix: vulnerability found by GitHub: CVE-2020-7774 #2686
- [x] Fix: vulnerability found by GitHub: CVE-2021-27290 #2673
- [x] Add comment for clarity #2671
- [x] Add SCV.Finance as an dApp #2668
- [x] Update contributors in README #2672
- [x] Make private func private #2675

Others
---
- [ ] Log more events to analytics #2581 — might be a bit less, let the previous sprints go live first
- [ ] Make errors more user friendly #2557 — implement when user-friendly versions are ready
- [ ] Samoa. Maybe.

**Comment by hboon** [comment]
Build 386
