### ISSUE TITLE
Scope for 16 Apr

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2701]
- [x] Add Wallet Naming feature in Settings #2679
- [x] Display user-friendly messages instead of cryptic RPC node errors #2709 — still adding FAQ entries, but shipping it as it is now because it is still clearer than the current version
- [x] Make enabling testnets and mainnets be exclusive. This is to prevent users from confusing them and hopefully lessen the possibility of users being scammed by thinking tesetnet balances have non-zero fiat value

Analytics
---
- [x] Log use of 'All Funds'
- [x] Log when user taps button to attempt to rectify send transaction error
- [x] Log use of TaiChi
- [x] Log opening blockchain explorer #2705
- [x] Log support options #2705
- [x] Log clear dapp browser cache #2705

Bug fixes
---
- [x] Fix: Oneinch (swap) service broken because web API is no longer valid #2712 
- [x] Return an empty array when failure to fetch contracts data, instead of failing whole TransactionInstance creating #2707
- [x] Remove animation when ActivityLoadingIndicatorView is hidden #2699
- [x] Fix: travis broken because config not updated with correct Cocoapods gem version #2690 
- [x] Fix: crash when taking a video during KYC for ramp.network #2694 
- [x] Fix: crash in My Wallet screen if mainnet is disabled #2689 
- [x] Fix: posting transactions with WalletConnect should show a pending transaction in the Activity tab like non-WalletConnect transactions #2695 
- [x] Attempt to fix crash in web3swift #2702

Internal
---
- [x] Improve code based on SwiftLint warning #2697 
- [x] Reduce SwiftLint warnings #2697 
- [x] Reduce compiler warnings #2697 
- [x] Remove no longer used code #2706 
- [x] Log errors accessing Ramp and Oneinch remotely #2713 
- [x] WIP — Samoa

**Comment by hboon** [comment]
TestFlight build 387
