### ISSUE TITLE
Scope for 30 Apr

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2718]
- [x] Use our own token image repo for all chains instead of just testnet #2737 
- [x] Show correct symbol and native crypto name (i.e. not always ETH and Ether) when displaying user-friendly error messages mapped from RPC node errors #2735 
- [x] Fix: special search keyword in wallet 'swap' returned wrong results #2732 

UI
---
- [x] Speed up actionsheet animation #2730 
- [x] Update icon for rename wallet cell in Settings #2727 
- [x] Fix: corner radius for user-friendly RPC errors actionsheet #2729 

Analytics
---
- [x] Log to analytics when user names their wallet #2731 

Internal
---
- [x] Make travis run tests with Xcode 12.4, on iOS 14.4 (where many users are now) #2738

- [ ] WIP — Samoa

**Comment by hboon** [comment]
TestFlight build 388
