### ISSUE TITLE
Scope for 14 May

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2741]
- [x] [Samoa] Use CoinGecko as pricing data source (paving the way for Samoa) #2687
- [x] Decode ERC20 approval transactions so they can be displayed as such in Activities tab #2394
- [x] Switch dapp browser search engine to duckduckgo. No ads — so fewer scams and more results shown top of the fold #2736
- [x] Fix: ERC20 approvals should appear as activities in Activity tab #2761
- [x] Fix: detecting of transactions for ERC20 approvals broken when downloading transaction history #2759
- [ ] WIP — Samoa #2747

**Comment by hboon** [comment]
Build 389
