### ISSUE TITLE
[Samoa] Umbrella: UI to display richer token data including, pricing and pricing history in a chart

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2747]
Let's build this and merge in separate PRs bit by bit. This is how it will ultimately look like: https://projects.invisionapp.com/share/7TZHRQ8W265#/screens/438941758

Original issue: #2630

- [x] Switch to CoinGecko for pricing data #2687
- [x] Build the Info tab for fungibles (native crypto + ERC20) and move the most recent 3 transactions into the Activity tab #2748
- [x] Modify the Activity sub-tab in token screen to show relevant Activities instead, with the correct UI and data #2749
- [x] Modify Wallet tab cells look and feel (no group/section) #2754
- [x] Add summary/total to Wallet tab #2755
- [x] New Wallet summary and selection screen #2756
- [x] Compute fiat value for each wallet while they are inactive #2802

Might not be implementable yet:

* Modify Wallet tab cells to add group/sections. Follow up to #2754
* Add Alert tab. Follow up to #2748

**Comment by vladyslav-iosdev** [comment]
@hboon can u remind me what is left for this issue?

**Comment by hboon** [comment]
@vladyslav-iosdev let’s close this for now since we have new issues discussing what was previously missing (alert and grouping)
