### ISSUE TITLE
Scope for 28 May

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2762]
Wallet and Activity tab
---
- [x] Fix: Auto-detect tokens and pick up transactions for Polygon, Binance, etc #2819
- [x] Show a "Swap" placeholder and "Contract Execution" placeholder in Activity tab. Swaps are group of transctions which include at least 1 receive and 1 send transaction — this needs more UI direction, but will have to do now to fix the logic first #2791 
- [x] Use etherscan compatible endpoints to fetch transaction history for Artis mainnet and testnet #2775 
- [x] Fix: etherscan-compatible endpoints for Fantom-testnet and Avalanche mainnet #2772 
- [x] Fix: activities (from events) are not shown in Activity tab, only transactions from Etherscan-compatible API if there are no activities downloaded when app is launched #2777 
- [x] Fix: ERC20 receive transactions are displayed wrongly with an additional (erroneous) receive ETH with the same amount #2770 

Growth
---
- [x] Prompt user to rate app after sending a transaction successfully #2796 

Samoa
---
- [x] Modify Wallet tab cells (FungibleToken, EthToken) look and feel #2754
- [x] Refresh wallet selection screen and make it also accessible via blockie in Wallet tab #2756
- [x] Token screen updated

UI
---
- [x] Rename Binance to Binance (BCS) #2780
- [x] Pasting something into AddressTextField should clear error state displayed if it's not an error #2781
- [x] Allow user to tap current wallet in account switcher. Just pop back to Settings tab #2764 

Other Fixes
---
- [x] Fix: Artis sigma1 wrongly treated as testnet #2773 
- [x] Fix: crash when we write and then read OpenSea data which is empty for a token #2801 
- [x] Fix: crash sometimes right after switch networks if price is refreshed just before the TokensStorage is destroyed #2803 
- [x] The title label in the screen showing a non-fungible screen should have a maximum width — handle when title is too long #2814

Internal
---
- [x] Make Travis use Xcode 12.5, was 12.4 #2795 
- [x] Remove unused code #2763
- [x] Remove unnecessary duplicate code
- [x] Make extract arguments from Transaction function calls be more explicit and safer #2760 
- [x] Move oneinchs execution to background queue #2787
- [x] Push target view controller for payments coordinator to appropriate navigation view controller #2785

**Comment by hboon** [comment]
Testflight build 390
