### ISSUE TITLE
Scope for 11 Jun

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2820]
Activity — transactions fetching and token auto detection
---
- [x] Fix: Heco mainnet and testnet explorer endpoints #2880 
- [x] Fix: Etherscan-compatible explorer webpage root for Callisto #2871 
- [x] Fixed token autodetection for several chains — ARTIS sigma1, ARTIS tau1, Sokol, Callisto, Binance and testnet, Heco and testnet, Mumbai testnet
- [x] Restore and fix support for Callisto #2829 

Analytics
---
- [x] Log what is the first action (create, import, watch wallet) for new installs #2833 
- [x] Exclude TestFlight builds from analytics #2832 

Signing
---
- [x] Fix: when a dapp asks to sign a transaction and has a bool in the payload, actionsheet doesn't appear #2857 

Samoa
---
- [x] Show prices for more tokens in Wallet tab and how they are displayed #2864
- [x] Improve token prices matching. Reduce false positives #2858 
- [x] Fix: Avalanche token price wasn't fetched #2853 
- [x] Use CoinGecko token prices for Fantom
- [x] Remove price ticker matching completely for unsupported chains to reduce erroneous matching #2847 
- [x] Fix: non-mainnets should not have fiat value #2811

Others
---
- [x] Below "Hidden Tokens" add another section called "Popular Tokens" #2845
- [x] Enable Polgyon chain by default #2848 
- [x] Add Optimistic and Optimistic Kovan chains #2841 

UI
---
- [x] Tweak add button in navigation bur #2885
- [x] Remove spurious tokens from Wallet tab #2831 

Internal
---
- [x] Clean up comments from AddHideTokensViewController #2886
- [x] Fix: custom RPCServer logic (no UI yet) #2881 
- [x] Reduce realm instances creation in incordinator #2875
- [x] Fix: Binance explorer APIs wrongly taken as Blockscout. Should be Etherscan #2873 
- [x] Standardize to use `startblock=` in Etherscan APIs as `startBlock=` only works with xxx.etherscan.io, but not BlockScout #2872 
- [x] Fix adding incorrect coordinator while changing wallets #2870 
- [x] Move ramp execution to background queue #2862
- [x] Refactor to make sending Etherscan API key clearer #2851 
- [x] Add comment for clarify about frequent "execution reverted" RPC node errors #2854 
- [x] Replace using TokenObject with TokenActionsServiceKey #2860 
- [x] Remove unused code
- [x] Rename bool variable/label to be more idiomatic #2849 
- [x] Add `.callisto` to `allCases`. Otherwise code might fail mysteriously #2843 
- [x] Fix build warnings  #2834

**Comment by hboon** [comment]
Build 391
