### ISSUE TITLE
Scope for 25 Jun

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2889]
- [x] EIP3085 wallet_addEthereumChain — i.e. dapps can request wallet/users to add a custom chain #2907
- [x] User manually add custom chain #2826
- [x] Improved NFT image display #2906
- [x] Improved support for ERC721 token detection and transaction fetching #2895 
- [x] Fix POAP (xDai) tokens display #2905
- [x] Fix: token images stored on IPFS was not displaying #2900 
- [x] Fix: sometimes actionsheet to sign transactions doesn't show up if the request includes unexpected parameters #2857
- [x] Now includes a list of popular tokens when adding a token manually, for convenience #2861
- [x] Improved Polygon support #2899
- [x] Restore support for Callisto #2871 #2843 
- [x] Remove spurious tokens from Wallet tab #2831

**Comment by hboon** [comment]
Build 395
