### ISSUE TITLE
Scope for 9 Jul

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2909]
- [x] Add prompt for subscribing to email list #2919 

RPC endpoints and transaction fetching
---
- [x] Update Polygon mainnet and testnet to use Infura for RPC. More stable (hopefully) #2948 
- [x] Fix: blockchain explorer endpoint for xDai. So no transactions were downloaded and token auto detection was broken #2942 
- [x] Update Polygon testnet explorer endpoints #2915 

Browser
---
- [x] Set `ethereum.chainId` in dapp browser. Some dapps (e.g https://omni.xdaichain.com/bridge) expect it #2952 
- [x] Make chain ID returned by `web3.version.getNetwork()` be hex encoded #2923 

Others
---
- [x] Improve ipfs: URL rewriting to be more forgiving #2951 — some (DOGE) fungible tokens metadata aren't displaying
- [x] Show error message to user when dapp uses EIP3085 to add a chain and the blockchain explorer root is invalid (or down) #2914 

Bug fixes
---
- [x] Fix: In the switch server screen, de-selecting every testnets should not bounce the user back to mainnet (testnet can't be enabled again, if that happens) #2943 
- [x] Fix: ERC721 token balance which has become 0 aren't zeroed-out correctly #2934 
- [x] Fix: Transfer ERC721 to self should not change the balance

Analytics
---
- [x] Log analytics: user's Dynamic Type setting #2927 
- [x] Log analytics: adding custom chain manually in Settings or via EIP3085 #2926 

Internal
---
- [x] Remove outdated TODO #2949 
- [x] Remove unused pods #2940 
- [x] Refactor: rename property to be more intention revealing #2939 
- [x] Simplify code. Easier maintenance #2938
- [x] Remove outdated comment #2937 
- [x] Simplify code #2936 
- [x] Add debugging code that lets us dump transaction data to a JSON file #2935 
- [x] Fix typo in func name #2930 
- [x] Refactor: rename var to remove leading _ #2929
- [x] Fix typo in func name #2928 
- [x] Fix typo in comment
- [x] Refactor: rename func to be more intention revealing #2925 
- [x] Improve encapsulation #2924 
- [x] Fix: missing non-English localization strings #2921 
- [x] Fix: SwiftLint warnings #2920 
- [x] Refactor `isTestFlight` check

Backlogged
---
- [ ] WIP — Samoa #2747
- [ ] Some more updates to the Activity UI. The data isn't expected to change anymore though. So if a transaction isn't listed in this build, it's either a bug or we can't get that data

**Comment by hboon** [comment]
Build 396
