### ISSUE TITLE
Scope for 23 Jul

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#2954]
- [x] [Samoa] Compute fiat value for each wallet while they are inactive #2802
- [x] Fix: Polygon native token not showing price #2968 
- [x] Add native token icons for Optimistic mainnet and testnet #2956

**Comment by AW-STJ** [comment]
Can we also add this #2808 and also log the events to using this Quickswap button?

**Comment by hboon** [comment]
Build 398

**Comment by hboon** [comment]
Forgot to close previously
