### ISSUE TITLE
Scope for 20 Aug

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-ios#3047]
- [x] Add Custom Linking to Quickswap for tokens on Polygon #2808
- [x] Add support for Cronos testnet
- [x] Update popular token list #3069 out from here: https://etherscan.io/tokens?sort=holders&order=desc
- [x] Design: Add email contact as a support channel back to iOS if it's still legit #2982
- [x] Samoa changes

Analytics
---
- [x] Log analytics: user's choice when prompted to subscribe for email newsletter #3024 

UI tweaks
---
- [x] Label swap buttons with just "Swap" #3037 
- [x] Update the design of Add Custom Token #2995
- [x] Improve the alignment of the graphic and text on the Seed Phrase intro screen #2986
- [x] Tweak backup intro screen layout #2998 
- [x] EnabledServersViewController, AccountsViewController should have a bottom inset when scroll to the bottom for phones with home bar (iPhone X and newer) #2931
- [x] Add some extra space below the Testnet button #2997
- [x] Add a paste button for importing private key and keystore JSON #2815
- [x] Improve the alignment of the graphic and text on the Backup intro screen #2985

Sending
---
- [x] Tapping send button doesn't work in TokenViewController presented from activities list #3056

Samoa
---
- [x] Build the Info tab for fungibles (native crypto + ERC20) and move the most recent 3 transactions into the Activity tab #2748
- [x] Improve Add/Hide Tokens screen #2994
- [x] Add summary/total to Wallet tab for current wallet #2755
- [x] Refactor: Improve updating `walletSummaryView` view #3078
- [x] update displaying historical price changes, changes percentage
- [x] remove `total, max supply` fieds from token info
- [x] Group tokens by chain in Wallet tab #2957

Internal
---
- [x] Refactor: extract ActivitiesView to separate file #3081
- [x] Fix ref cycle for activities view #3011
- [x] Refactor: `SendCoordinator` remove unused dependencies #3075
- [x] Refactor: Update WalletBalanceFetcher with updated code base from TokensDatastore #3068
- [x] Refactor `EventSourceCoordinator` and `EventSourceCoordinatorForActivities` with `.functional` extension, fix crash: converting `Int` from `BigUInt`, fixed with replacing `Int` with `String`  #3011
- [x] Refactor: use Promise instead of completion #3070 
- [x] Refactor: Remove token sorting duplication #3066
- [x] Fix: SwiftLint warnings #3000 
- [x] Fix build warnings. Replace protocol inheritance of `class` with `AnyObject`. Former is deprecated
- [x] add measuring code execution, improve activities filtering
- [x] Add promise alternative of function which uses completion block #3080 
- [x] Improve adding transaction to db, remove `waiting for closing ui screens` #3061

Fixes
---
- [x] Fix index out of range crash on tokenHolders[0] inActivitiesService #3073
- [x] Fixes crash of `null pointer` when switch bettwen wallets  #3011
- [x] Fix: typo in var name #3060 
- [x] Fix: "Add token failure" error when tap to add popular tokens in Add/Hide token screen #3050 
- [x] Fix sorting activities by dates #3042
- [x] Fix: when specifying native crypto token as input for Uniswap, use "ETH" instead of 0x00.00 because Uniswap likes it that way #3038 
- [x] Fix: crash in transaction data decoding #3036 
- [x] Fix: WalletConnect should be spelled without a space in it #3035 
- [x] Fix: Realm crash because: "Realm accessed from incorrect thread." #3028 
- [x] Fix: when auto-detected icons show up on the screen the first time in the Wallet tab (and cells are re-used), the token image shown might be wrong, from another token #3027 
- [x] Fix: broken test build #3026 
- [x] Fix: Users should not be allowed to change the gas price and limit on Optimistic chains #3023 
- [x] Fix: remove duplicate ETH token for Optimistic mainnet and testnet — remove the native token when the ERC20 equivalent is in the database #3020 
- [x] Fix: single transaction screens not taking decimals into account when displaying transaction value. Activity screen does #3014 
- [x] Fix: broken test build #3010 
- [x] Fix: vulnerability found by GitHub: GHSA-jxhc-q857-3j6g #3003 
- [x] Fix: test breaks when running in the entire suite, but works when running by itself
- [x] Add test case for `RPCServer.displayOrderPriority` #3002 
- [x] Crash when tap to show a Hidden Token in Add / Hide Tokens screen #2933
- [x] Swipe to show swipe menu not working in Wallets screen opened from Wallet tab #2916
- [x] Watching an invalid Ethereum address should not crash #3029
- [x] Rename function to be more intention revealing #3051 
- [x] Crash when fetching events #3046

**Comment by hboon** [comment]
Build 399
